### ISSUE TITLE
This example does not work.

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/object-attributes-tutorial#2]
class Person

  def name=(str)
    @name = str
  end

end

puts avi = Person.new
#=> #<Person:0x007fb4dc81add8>
avi.name = "Avi Flombaum"
puts avi
#=> #<Person:0x007fb4dc81add8 @name="Avi Flombaum">

**Comment by garettarrowood** [comment]
I think its the "puts."  I think both "puts" just need to be deleted.

**Comment by aviflombaum** [comment]
@garettarrowood  No, it is meant to be broken - the next section covers adding the `#name` method to read the data out of the `@name` instance variable. The example you refer to should mention that it will break, but that our desire, our target output, would be the person's name.

**Comment by garettarrowood** [comment]
@aviflombaum I think I understand what you mean. But here is what my irb shows using puts...

<img width="404" alt="screen shot 2015-07-29 at 11 14 06 am" src="https://cloud.githubusercontent.com/assets/12770108/8961410/065d24aa-35e3-11e5-8437-e56210e4f406.png">

line 11 is: puts avi
line 12 is: avi

The "puts avi" doesn't display the @name attribute like the example does.  However the "avi" does show the attribute.  Also, using the puts adds unnecessary nil returns.

**Comment by AnnJohn** [comment]
Closing issue
